-- DROP EXISTING TABLES 
DROP TABLE IF EXISTS performance CASCADE;
DROP TABLE IF EXISTS watch_list_items CASCADE;
DROP TABLE IF EXISTS watchlist CASCADE;
DROP TABLE IF EXISTS alerts CASCADE;
DROP TABLE IF EXISTS position CASCADE;
DROP TABLE IF EXISTS holding CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS instrument CASCADE;
DROP TABLE IF EXISTS account CASCADE;
DROP TABLE IF EXISTS client CASCADE;